README.md: mention Debian and Ubuntu packages
jonathanio/update-systemd-resolved pull request #112
Opened 2023-03-08 07:33 UTC by perlun

2023-07-18 17:20 UTC, tomeon commented on README.md
> +[Ubuntu](packages.ubuntu.com/openvpn-systemd-resolved) also provides a `.deb`
Nit: could you please include the scheme in this URL, for consistency with other links?

2023-07-18 17:22 UTC, tomeon requested changes
Nit: could you please include the scheme in the `packages.ubuntu.com` link, for consistency with other links in the README?

2023-07-21 15:00 UTC, tomeon approved these changes

2023-07-21 15:00 UTC, merged

2023-08-18 10:30 UTC, perlun commented
> Nit: could you please include the scheme in the `packages.ubuntu.com` link, for consistency with other links in the README?

Ah, was it a URL without scheme? :thinking: Anyway, thanks for fixing & merging. :bow: