Don't rely on command parameters as they seem unstable
jonathanio/update-systemd-resolved pull request #55
Opened 2018-10-25 12:50 UTC by tbaumann

Command paramter seem in flux as 2.4.6 passes different arguments than this script expected.
OpenVPN passes script_type and dev into the helper via ENV.

Fixes https://github.com/jonathanio/update-systemd-resolved/issues/54

2018-10-25 13:29 UTC, tomeon requested changes
Take a look at the [conditional at the very end of the script](https://github.com/jonathanio/update-systemd-resolved/blob/af334c3c5b27a166b97d02f960af4d1450b5f494/update-systemd-resolved#L412-L416):

```sh
if [[ "${BASH_SOURCE[0]}" == "$0" ]] || [[ "$AUTOMATED_TESTING" == 1 ]]; then
  set -o nounset

  main "${script_type:-}" "${dev:-}" "$@"
fi
```
The `script_type` and `dev` variables set by OpenVPN when invoking this script end up as the first and second positional parameters to `main`.  The parameter expansions `"${script_type:-}"` and `"${dev:-}"` need to be eliminated from the `main` invocation for your changes to `main` itself to work as expected.

2018-10-25 14:45 UTC, jonathanio commented
Can you describe the issue you are trying to solve? What has changed in the handling of the `up`/`down` script in 2.4.6, and what errors are you seeing as a result?

2018-10-25 14:51 UTC, tbaumann commented
OpenVPN starts the script like: `/etc/openvpn/scripts/update-systemd-resolved tun0 1500 1555 10.235.97.2 255.255.255.128 init`
Which causes the 'Invalid script type' error message. I assumed because $1 is wrong.

But what @tomeon showed me now makes me question that logic a bit. But the truth is, it just worked once I remove those lines. :smile:

2018-10-25 14:54 UTC, tbaumann commented
log
```
Thu Oct 25 14:15:45 2018 TUN/TAP device tun0 opened
Thu Oct 25 14:15:45 2018 TUN/TAP TX queue length set to 100
Thu Oct 25 14:15:45 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Thu Oct 25 14:15:45 2018 /sbin/ip link set dev tun0 up mtu 1500
Thu Oct 25 14:15:45 2018 /sbin/ip addr add dev tun0 10.235.96.135/25 broadcast 10.235.96.255
Thu Oct 25 14:15:45 2018 /etc/openvpn/scripts/update-systemd-resolved tun0 1500 1555 10.235.96.135 255.255.255.128 init
<11>Oct 25 14:15:45 update-systemd-resolved[9417]: Invalid script type: 'tun0'. Usage: update-systemd-resolved up|down device_name.
Thu Oct 25 14:15:45 2018 WARNING: Failed running command (--up/--down): external program exited with error status: 1
Thu Oct 25 14:15:45 2018 Exiting due to fatal error
```

2018-10-25 15:14 UTC, tbaumann commented
@tomeon Thanks for the hint. Happy with this?
```
  main "${script_type:-}" "${dev:-}" "$@"
```
vs
```
  main $@
```

2019-01-03 12:48 UTC, jonathanio commented
I've had a look into this and I cannot replicate this issue. I'm running 2.4.6 on my machine currently and the script is working as expected:

`Jan 03 12:26:27 gwrhyr openvpn[13459]: /etc/openvpn/scripts/update-systemd-resolved tun0 1500 1553 10.8.1.11 255.255.252.0 init
Jan 03 12:26:27 gwrhyr openvpn[13459]: <14>Jan  3 12:26:27 update-systemd-resolved: Link 'tun0' coming up
Jan 03 12:26:27 gwrhyr openvpn[13459]: <14>Jan  3 12:26:27 update-systemd-resolved: Adding DNS Routed Domain .
Jan 03 12:26:27 gwrhyr openvpn[13459]: <14>Jan  3 12:26:27 update-systemd-resolved: Adding IPv4 DNS Server 10.8.1.1
Jan 03 12:26:27 gwrhyr openvpn[13459]: <14>Jan  3 12:26:27 update-systemd-resolved: SetLinkDNS(7 1 2 4 10 8 1 1)
Jan 03 12:26:27 gwrhyr openvpn[13459]: <14>Jan  3 12:26:27 update-systemd-resolved: SetLinkDomains(7 1 . true)`
```

Reviewing the code, it is currently correct. As far as I can tell, for some reason, your version of OpenVPN is not correctly setting `$script_type` in the environment before calling the command. Given that `main` passes this explicitly from the environment (as noted by @tomeon above) the error is in effect correct. We don't rely on the command line parameters, but as `$script_type` has not been set, and even though it is passed inside quotations, `main()` is skipping the empty option, so the wrong error message is provided.

I'm happy for the `local` setting inside `main()` to be removed, and in fact the call of `main "$@"` doesn't even require any parameters in this case as we do not use anything provided by the command line - setting it to `main` only will be fine. We just need to be careful that the tests still run, as we don't explicitly export any of the settings, but as we don't `fork()` when we run the tests it should be OK.

2019-05-19 13:28 UTC, jonathanio commented
I'm closing this now as I've added a version of this change under commit 55c7144d91f10ca7ef20372f731692e0798dfd10.

2019-05-19 13:28 UTC, closed without merging